### ISSUE TITLE
The middleware can not update the value of the storeId variable

### ISSUE THREAD

**Issue by talissonf** [ecomclub/express-app-boilerplate#1]
https://github.com/ecomclub/express-app-boilerplate/blob/11425b06af8804444ac752f66d3333d9e1abfc32/app/bin/web.js#L30
@leomp12 The middleware updates the value of the storeId just inside the function. When next () calls the next function the storeId variable remains undefined outside the middleware scope.

**Comment by leomp12** [comment]
My fault, we may use ```req.storeId``` instead.
I'll update it, thanks.

**Comment by leomp12** [comment]
https://github.com/ecomclub/express-app-boilerplate/commit/a3bebaa30602093e6cc95f120ce9bd57906d16b8
